spring:
  application:
    name: homezz-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/homezz
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: health,beans
server:
  error:
    include-message: always
application:
  security:
    jwt: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000